version: 1.0.{build}

image:
- Visual Studio 2019
- ubuntu

build_script:
  - cmd: docker build -t jenkins-agent-windows .\windows
  - sh: docker build -t jenkins-agent-linux ./linux

services:
- docker

# artifacts:
#   - path: '*.tag.gz'

# after_build:
#   - cmd: docker save jenkins-agent-windows --output jenkins-agent-windows.tar.gz
#   - sh: docker save jenkins-agent-linux --output jenkins-agent-linux.tar.gz
#   - ps: Get-ChildItem .\*.tar.gz | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }